version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
        reservations:
          cpus: '0.01'
          memory: 30M

  api:
    image: pysatellite/dj-api
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=api.dj26.io
      - VIRTUAL_PORT=80
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 6M
